import Link from "next/link"
import type { JobPostingContentProps } from "../../../typings/common.interfaces"
import Button from "../../ui/Button"
import JobCardInfo from "../../ui/JobCard/JobCardInfo"
const JobPostingContent: 
React.FC<JobPostingContentProps> = ({
  info,
  contentBody,
  requirementsBody,
  requirementsList,
  tasksBody,
  tasksList,
  website
})=> {
  return(
    <article
      data-testid="page-content"
      className="
        bg-white
        dark:bg-very-dark-blue
        mt-6
        max-w-[90%]
        xl:max-w-[1100px]
        rounded-lg
        mx-auto
        p-6
        md:p-10
      "
    >
      <div 
        className="
          md:flex
          md:items-center
          md:justify-between
          w-full
        "
      >
        <JobCardInfo 
          postedAt={info.postedAt}
          position={info.position}
          location={info.location}
          contract={info.contract}
          isContent={true}
        />
        <Link href={website}>
          <a
            data-testid="apply-button"
            className="
              md:mb-8
            "
          >
            <Button
              type="primary"
            >
              Apply Now
            </Button>
          </a>
        </Link>
      </div>
      <p
        data-testid="content-body"
        className="
          body
          text-dark-gray
          my-8
          md:my-0
          md:mb-8
        "
      >
        {contentBody}
      </p>
      <h3
        data-testid="content-requirements-title"
        className="
          py-3
        "
      >
        Requirements
      </h3>
      <p
        data-testid="content-requirements-body"
        className="
          body
          text-dark-gray
          my-6
        "
      >
        {requirementsBody}
      </p>
      <ul
        data-testid="content-requirements-list"
        className="
          px-4
          pb-6
        "
      >
        {requirementsList.map(requirement=>{
          return(
            <li
            className="
              list-disc
              pl-5
              text-dark-gray
              font-light
              mb-3
            "
            >
              {requirement}
            </li>
          )
        })}
      </ul>
      <h3
        data-testid="content-tasks-title"
        className="
          py-3
        "
      >
        What You Will Do
      </h3>
      <p
        data-testid="content-tasks-body"
        className="
          body
          text-dark-gray
          my-6
        "
      >
        {tasksBody}
      </p>
      <ul
        data-testid="content-tasks-list"
        className="
          px-4
        "
      >
        {tasksList.map(task=>{
          return(
            <li
            className="
              list-disc
              pl-5
              text-dark-gray
              font-light
              mb-3
            "
            >
              {task}
            </li>
          )
        })}
      </ul>
    </article>
  )
}

export default JobPostingContent